---
- name: Install and start application
  hosts: Rhel
  become: true

  tasks:

  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/jrswanson4/RhelAppDemo.git 
      dest: /home/ec2-user/DemoProject
