---
- name: Install and start application
  hosts: Rhel
  become: true

  tasks:

  - name: intsall git
    ansible.builtin.dnf:
      name: git
      state: present

  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/jrswanson4/Summit_Kiosk_Site.git 
      dest: /home/ec2-user/DemoApp
      clone: yes
      update: yes 

  - name: install node
    ansible.builtin.dnf:
      name: nodejs
      state: present 

  - name: install npm
    ansible.builtin.command: chdir=/home/ec2-user/DemoApp sudo npm install

  - name: start app
    ansible.builtin.command: chdir=/home/ec2-user/DemoApp sudo npm start
    async: 30
    poll: 5 

  - name: check connection
    ansible.builtin.uri:
      url: http://localhost:3000 

  
    


    

